import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import Sidebar from '@/components/Sidebar';
import Header from '@/components/Header';
import SidebarProvider from '@/provider/SidebarProvider';
import LayoutContainer from '@/components/LayoutContainer';
import DMThemeProvider from '@/provider/DarkModeProvider';

const inter = Roboto({ subsets: ['latin'], weight: ['100', '300', '400', '500', '700'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${inter.className} min-h-screen bg-primary-nude dark:bg-secondary-black`}>
                <DMThemeProvider>
                    <SidebarProvider>
                        <Sidebar />
                        <LayoutContainer>
                            <Header />
                            {children}
                        </LayoutContainer>
                    </SidebarProvider>
                </DMThemeProvider>
            </body>
        </html>
    );
}
